### ISSUE TITLE
Copy and paste structures into Marvin

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#1]
I often copy the molfile from the database and paste it into the marvinSketch window on my desktop for editing. It would be useful to have this feature in this marvin version.

(This would also be good for the interface!)

**Comment by mnowotka** [comment]
You can do it, it works exactly as you want.

**Comment by mnowotka** [comment]
This works now so I'm closing this issue. Formats other then molfile should be supported as well so I've created separate enhancement issue: https://github.com/chembl/curation-interface/issues/50.
