### ISSUE TITLE
Change Molecule Features to Drug Icons

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#10]
I would change the label in http://sark.ebi.ac.uk:3021/curation/curate#16789 from 'Molecule Features' to 'Drug Icons' so users know this can only be edited if the compound is a drug. 

Then also change 'Properties' in the Records list to 'Drug Icon Properties' or something that would let users know that they can edit the icons here, if it is a drug.

**Comment by mnowotka** [comment]
Done.
