### ISSUE TITLE
When entering multiple records to split, I got this error in FireFox

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#102]
I selected 4 records to split and got this error message 

![error](https://cloud.githubusercontent.com/assets/9843928/5341825/0742ad1c-7ef1-11e4-9383-3d50277ac0b4.jpg)

NOTE: This also happens in Chrome

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
No, I couldn't add more than this many characters:

 "3123,3434,555,6666,7"

**Comment by ljbellis** [comment]
This was in Chrome

**Comment by mnowotka** [comment]
Was the error message the same or no message but you just couldn't enter more characters?

**Comment by ljbellis** [comment]
I just couldn't enter any more characters

**Comment by mnowotka** [comment]
OK, thanks, I will fix that.

**Comment by mnowotka** [comment]
It should be fixed now, please check.

**Comment by ljbellis** [comment]
yes
