### ISSUE TITLE
No RECORD_DRUG_PROPERTIES table in the app schema.

### ISSUE THREAD

**Issue by mnowotka** [chembl/curation-interface#106]
So far I was running the curation interface on app schemas up to version 18. There is some logic in my code relying on the RECORD_DRUG_PROPERTIES table, which is now missing. What should I do then?
- change my code (but I don’t know exactly how)
- switch to some other schema, which has this table (which one?)
- ask you to copy this table to app schema (but why it wasn’t there in the first place?)

**Comment by ljbellis** [comment]
Although we will be giving this interface to people external to ChEMBL and would therefore not want them to see various tables, I think we should keep the tables as they are in ChemPro. I downgrade compounds and set this flag in the Molecule_Dictionary table but in the App schema, this column (downgraded) isn't shown at all. 
Is there some way that we can have the full 'ChemPro-like' set up but maybe _hide_ various tables depending on who the user is?
