### ISSUE TITLE
'Merge' button not working as expected

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#113]
I drew a compound I knew was in ChEMBL.

I clicked on Save.

I chose the option for Merge.

It then expects me to put in the records I want to merge.

However, a merge is a total move with a downgrade of the original compound. 

If you want them to put in record_ids, then at least have another check box next to it for 'All Records'?

![merge](https://cloud.githubusercontent.com/assets/9843928/8057417/0c58d3a6-0ea9-11e5-9d2b-3e9575da3295.jpg)

**Comment by ljbellis** [comment]
Is this closed because you're working on something else?

**Comment by mnowotka** [comment]
This was closed on 11 Jun - I don't remember why I would assume we agreed to close this one but feel free to reopen it this is not the case.

**Comment by ljbellis** [comment]
I have no clue why it was closed - there was never a discussion that I can remember.
