### ISSUE TITLE
The hyperlink for existing compounds isn't very obvious

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#116]
It would be good if the hyperlink would be more obvious as it's a great feature to have

![hyperlink](https://cloud.githubusercontent.com/assets/9843928/8057622/e64107a4-0eaa-11e5-8810-73c2d12be2e1.jpg)

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes this is more obvious
