### ISSUE TITLE
Existing Compound - Click on New Record then Cancel

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#117]
I have drawn a compound which exists in ChEMBL and clicked on save.

Action Required box pops up and I click on New Record.

I realise that I don't want to add a new record so I cancel this pop up.

I expect to go back to the Action Required box (seeing as it's behind the new record pop up) but Cancel closes both boxes.

I would like the Action Required box to remain so that I can choose another option.

![new record](https://cloud.githubusercontent.com/assets/9843928/8058166/691220e2-0eaf-11e5-9016-1f2aa5e1aee4.jpg)

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes, this works. Thanks.

**Comment by ljbellis** [comment]
yes
