### ISSUE TITLE
Can't edit compound properties in Curate window

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#12]
I would expect all of the Curate page (http://sark.ebi.ac.uk:3021/curation/curate#16789) to be editable as standard or at least an explanation as to why part isn't editable.

So, for Compound Properties perhaps you could have a line stating 'Calculated From Structure' and if you alter the structure because it's wrong, there could be a button that says 'Recalculate From Structure' or something?

If it can't be edited, then you could always leave it out. If the user can't do anything with it then no point it being there.

**Comment by mnowotka** [comment]
I've added 'Calculated From Structure'  description below 'Compound Properties' header.
Properties can only be modified by editing the structure in Marvin sketcher. The same is true for structure and image. About leaving out some regions in the `curate view` - I've created new enhancement issue: https://github.com/chembl/curation-interface/issues/52
