### ISSUE TITLE
When Splitting records, you can input a record_id that doesn't exist

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#120]
Draw in a compound which doesn't exist, then choose to SPLIT

In split, put in a ChEMBL ID, eg. 112 and then choose find records. 

Then add a record id to the field which isn't one of those associated with CHEMBL112

Initially, the compound is saved.

Then there is an error - which is not descriptive as to why there is an error.

Then another error window telling them to contact ChEMBL Help

![incorrect rec id](https://cloud.githubusercontent.com/assets/9843928/8058742/739ff27e-0eb3-11e5-838b-cc35c2654f95.jpg)

![save success](https://cloud.githubusercontent.com/assets/9843928/8058744/7781e046-0eb3-11e5-8ec9-fcde79ce0369.jpg)

![destroy](https://cloud.githubusercontent.com/assets/9843928/8058747/7b3c69a4-0eb3-11e5-85ac-178f31dfe280.jpg)

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
yes
