### ISSUE TITLE
Adding a new Document

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#121]
When you are creating a new document to add to the database, the top dropdown box has:
BOOK
DATASET
PUBLICATION 

as the three choices.

The chances of us adding a book is very very small. 

Also, Publication is quite generic. I think it would be better to change this to paper.

So, please can this be changed to (in this order, with Paper as default):

PAPER
DATASET
BOOK

??

**Comment by ljbellis** [comment]
Happy to leave PULICATION as it is. But can we change the order ?

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
yes this is fixed, thanks.

**Comment by mnowotka** [comment]
OK, I'm closing this one.
