### ISSUE TITLE
The cursor changes from an arrow to an i-beam pointer in the Choose Source window

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#122]
When choosing which source to add for a new compound, the arrow cursor changes to an i-beam pointer when you hover over the names of the sources.

This isn't a massive thing but it just looks odd.

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes this has changed

**Comment by mnowotka** [comment]
OK, in that case I'm closing this.
