### ISSUE TITLE
Creating new source allows me to put in a PubMed ID that has no relation to the inputted source information

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#123]
I created a new compound, then added it to the source of Harvard Malaria Data and then added a document of complete nonsense (kjlfdghf sdhfjdgjhd kdfdjh) but linked it to a PubMed ID of 112234 which is nothing to do with the nonsense.

it then allowed me to save the information and it said save successful.

However, a number of seconds later, it came up with an error message and said contact ChEMBL Help.

Can it be changed so that if the DOI and PubMed fields are filled in and the other fields are filled too, the system checks that the data from the PubMed ID matches the inputted information?

Also, it still saves the document as a source and when you try to click again, it 'saves' it but then causes an error. You have to refresh to cancel the source which wipes the structure and if you've hand drawn the structure, like i normally do, this is also cleared and youhave to start again!

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes
