### ISSUE TITLE
You can type over the Source in the Add New Compound Record

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#125]
Find a known compound in ChEMBL
Go to its edit compound page
Add a new record by using the Add New Compound Record box.
Go to Find Document and choose Default

At this point it is feasible that maybe you would like to add your own source that isn't in the list. For whatever reason.
You can directly type over the contents of the list. It does tell you that whatever you have typed isn't in the list but allows you to keep it there.

You can then click on OK and it is saved.

When you go back to the compound page, the new record is there but it has given it a source of AstraZeneca due to that being the first source in the list. This needs to be fixed.

I would say that you should be allowed to overwrite this source list and that the source is then recognised and saved internally. <--- This is more for external people. For us, I would say remove the ability to overwrite altogether.

![unpublished](https://cloud.githubusercontent.com/assets/9843928/8060285/4dad4432-0ebc-11e5-9993-5f55189bb59d.jpg)

![az](https://cloud.githubusercontent.com/assets/9843928/8060287/50fd9c18-0ebc-11e5-9533-b511db89fb14.jpg)

**Comment by mnowotka** [comment]
I'm linking this with https://github.com/chembl/curation-interface/issues/127 as they can be solved in one go.

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
I can't overwrite. It won't save. 

However, the error message is wrong. It says the source named null, but it's not null, you've typed it. Maybe a better error message is 'INCORRECT SOURCE ENTERED" or something?

![source](https://cloud.githubusercontent.com/assets/9843928/9195683/a7ab6da6-401c-11e5-9f4f-2347d286a71a.jpg)

**Comment by mnowotka** [comment]
Sure, no problem.

**Comment by mnowotka** [comment]
The description has been changed.

**Comment by ljbellis** [comment]
thanks
