### ISSUE TITLE
You can add a downgrade reason for a compound even if it's not downgraded

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#126]
I can type a downgrade reason into the compound page, even if the compound isnt downgraded.

Can this option be hidden until Downgrade = YES?

![downgrade](https://cloud.githubusercontent.com/assets/9843928/8061015/773ca9e2-0ec0-11e5-81b4-d86b7d7cad84.jpg)

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes this is fixed.
