### ISSUE TITLE
Lets me create a new document that is totally blank

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#130]
Enter a new compound.

Insert as new.

Then in the create document box, just click on create with all blank fields.

It allows you to do this, says that it is saved and then after a few seconds it gives a non-informative error

**Comment by ljbellis** [comment]
Mandatory:

Type
Title
Author
Year

thanks

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes
