### ISSUE TITLE
The molregno is not used again if the compound was destroyed

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#131]
Draw in a new compound and then save it.

It's saved as, for example, 1798649.

If for some reason it then gets deleted, due to an internal server, error, if you try and resave it, it is saved as 1798650. 

If the new compound is destroyed then the number should be used again.

**Comment by mnowotka** [comment]
This is a bit out of scope of this project. Incrementing sequences happens on DB level and it's not trivial to reverse, hopefully we will reduce error rate so there won't be too much gaps anyway.
