### ISSUE TITLE
Uploaded multiple molfiles and want to save them all

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#135]
I have uploaded 5 separate molfiles to the interface into the box to the right.

I then click on Save All To ChEMBL

and I get a window asking me if I want to clean the molecule. However, it doesn't say which molecule is being cleaned. 

This isn't a major thing but it would be useful if it could pick up the filename??

![clean](https://cloud.githubusercontent.com/assets/9843928/8078994/951d7f42-0f59-11e5-8697-ca0e6e009cff.jpg)

**Comment by mnowotka** [comment]
This one is fixed now. Please check.

**Comment by ljbellis** [comment]
Yes it shows the name
