### ISSUE TITLE
Need Replacement_MRN in the Downgrade section

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#14]
When I downgrade a compound, 99% of the time it is replaced with another. Either because it's wrong or because it was lacking stereo etc.

Showing the replacement_mrn (or ChEMBL_ID) is very important so the user can make the decision to use the compound they have searched for and found to be downgraded, or whether to reinstate the downgraded one.

**Comment by mnowotka** [comment]
Replacement molregno can be found in 'Meta' box in the `curate` view.

**Comment by ljbellis** [comment]
Yes I know, but it needs to be in the Downgraded section. Please can you move it?

**Comment by mnowotka** [comment]
Sure! Will do.

**Comment by ljbellis** [comment]
Many thanks

**Comment by mnowotka** [comment]
Done.

**Comment by ljbellis** [comment]
Yes done, thanks.
