### ISSUE TITLE
Failed importing document from PDF.

### ISSUE THREAD

**Issue by mnowotka** [chembl/curation-interface#140]
Louisa has send this to me already.

**Comment by ljbellis** [comment]
10.1021/jm501

**Comment by ljbellis** [comment]
did work: 10.1021/ci400099q

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Whilst I can paste that DOI into the DOI field and it works, I have tried to import from a PDF saved on my computer and it's not working properly. It just said 'scanning pdf' and was like that for about 10 mins before I cancelled it

**Comment by mnowotka** [comment]
Great! Can you put it into our Dropbox folder? I'm happy to look at it to cover as many strange PDFs as possible. In this issue I was testing RSCpaper.pdf (https://www.dropbox.com/s/uvtyeumeifwsbd6/RSCpaper.pdf?dl=0) file which you told me doesn't work and now it works for me.

**Comment by ljbellis** [comment]
hrere:

https://www.dropbox.com/s/vl9ay98bt5h7bj6/jm950541c.pdf?dl=0

**Comment by mnowotka** [comment]
Thanks, I will fix that.

**Comment by mnowotka** [comment]
I think this is now fixed.
