### ISSUE TITLE
After adding a new document and clicking on 'OK', the window does not close

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#142]
I added a new compound, and then added a new document.
When I clicked on OK, I got a message to say it had saved correctly and the ChEMBL ID and Document ID were populated. However, the window did not close. I had to click OK again for it to close.

![notclosing](https://cloud.githubusercontent.com/assets/9843928/9195027/acff070e-4017-11e5-8049-aff20cb2bf4f.jpg)

**Comment by mnowotka** [comment]
Yes, this is exactly what you requested for in your earlier ticket. Let me find it for you.

**Comment by mnowotka** [comment]
This is where you requested for this behavior: https://github.com/chembl/curation-interface/issues/67

**Comment by ljbellis** [comment]
Hmmmmm, yes I can see where the confusion is.

Last time, it would just close without telling you that anything had really happened. 

Also, I keep going on about the 'CREATE' button. This is confusing as well. 

I would say that this would be better if:

You add all your information and click on OK. You then get a new pop up window which says "Your document was saved as CHEMBL123456, Document ID 85455"

Otherwise you're clicking twice in the same place.

**Comment by ljbellis** [comment]
yes
