### ISSUE TITLE
When adding a PubMed ID and searching on it, DOI is populated with same ID

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#144]
I added a new record into my new compound page and went to Find Document.

I then used 123456 as my PubMed ID to find the document.

When it was found, it automatically populated the DOI field with this value, which is incorrect.
![doi](https://cloud.githubusercontent.com/assets/9843928/9195139/798721b2-4018-11e5-89b6-408c5af2f8ef.jpg)

**Comment by ljbellis** [comment]
For clarification - the DOI field is being populated with the SAME input at the PubMed ID, rather than finding the associated DOI from the publication. 

In an earlier issue, I requested that they be populated from the publication, not that the DOI is populated with the same input.

**Comment by mnowotka** [comment]
Yes, I understand, I will check that.

**Comment by mnowotka** [comment]
Fixed, please check.

**Comment by ljbellis** [comment]
yes
