### ISSUE TITLE
When I draw a compound that already exists and choose SAVE - I expect other buttons

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#145]
I drew in a compound which already exists and clicked on Save.

I got the "Compound already exists:" window.

Now, the OK button and the X at the top right do the same function, in that they close the window.

The other button is EDIT. 

Please can you change this to CURATE to match the request in 

https://github.com/chembl/curation-interface/issues/112

Please can you remove the OK button as well as the X closes the window.

I kept clicking on OK thinking that it would take me to the compound page.

![ok](https://cloud.githubusercontent.com/assets/9843928/9195488/1d50fed8-401b-11e5-88cf-483da2c0ed6b.jpg)

**Comment by mnowotka** [comment]
This issue doesn't introduce anything new that wasn't mentioned in https://github.com/chembl/curation-interface/issues/112. I would like to keep this discussion in one place so I'm closing this one.
