### ISSUE TITLE
When cancelling a new compound insert you get errors

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#15]
I drew a compound that I knew wasn't in chembl and then clicked on Save All To ChEMBL. 

I chose to add a new compound and then when it asked me to link to a document type, I changed my mind about adding the structure and pressed Cancel.

I was taken back to the original page but I then got an Error Message about it not being saved and then a confirm that it was saved to the Molecule_DIctionary. 

Now, if I had drawn this wrong and only noticed as I was choosing the document type, I should be able to cancel without it being loaded into the database.

**Comment by ljbellis** [comment]
It turns out that it was saved, even though you get "Error with saving compound" message. So when I tried to save it again, I got more errors until I searched for a matching structure and found it in ChEMBL!!

**Comment by mnowotka** [comment]
I can't reproduce this one. Again, I need some more info.

**Comment by mnowotka** [comment]
Fixed, please verify.
