### ISSUE TITLE
Can't drag more than one file to the molfiles box

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#151]
When trying to load more than one molfile file to the interface, it won't let me do it more than one at a time. This is frustrating - especially if I had about 100, which is my usual number.

![copy](https://cloud.githubusercontent.com/assets/9843928/9220057/94c43478-40d7-11e5-95dc-f42eba88144c.jpg)

**Comment by mnowotka** [comment]
Yes, this is a browser limitation and it's impossible to fix.
Seriously, we've spend a long time thinking about this and this limitation of one file is the best thing in the trade between functionality, complexity and some other technical consequences.

**Comment by ljbellis** [comment]
Then I can't see me using this feature for molfiles.

**Comment by mnowotka** [comment]
OK, so this is a critical issue, you can't see yourself using this feature without this fix, does it mean we should abandon the concept of developing curation interface here?

**Comment by ljbellis** [comment]
Developing the curation interface as a whole is the big picture. There is no need to jump to your conclusion from my comment just because I say that I would not use this feature for molfiles.

This is just one feature out of many that you've added. It will be useful for an SDFile or PDF, but I cannot see myself using it for individual molfiles, in the way I currently work. For example, at the moment I have 87 molfiles that I have redrawn. Each time I drag a file from my folder over to the window, the file window closes. To drop another, I have to reopen the file window, choose, drag and then drop. I can't see myself doing this 87 times when I could go to Knime or Pipeline Pilot and turn it into an SDFile - probably with less effort.
