### ISSUE TITLE
Error While Saving Compound Message

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#16]
Error message = 'Error message: An internal server error occurred. Please contact ChEMBL help.'

Would be good to have the ChEMBL Help email here so that people don't have to hunt around for it, or at least a hyperlink?

**Comment by mnowotka** [comment]
For reporting bugs and issues this issue tracker will be used. In the top menu of the Curation interface there is an item called: 'Help'. There are a 'Feedback', 'Repository' and 'About' subitems made just for this purpose.

**Comment by ljbellis** [comment]
Then maybe you should change the message to 

"Error message: An internal server error occurred. Please use the Feedback system (found under Help) to report this issue"

**Comment by mnowotka** [comment]
OK.
