### ISSUE TITLE
Adding a new source

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#17]
I added a new source, clicked on OK, I got the confirmation box pop up but the original 'Add New Source Box' stayed on top.

In fact, I kept clicking OK and created 7 sources of the same name.

To get rid of the box, I clicked Cancel and then had to scroll to see if it had been created.

**Comment by mnowotka** [comment]
Fixed, please refresh and verify.

**Comment by ljbellis** [comment]
This works. thanks
