### ISSUE TITLE
The journals aren't in alphabetical order

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#18]
When I was scrolling through the journals for my new source, they weren't in order.

**Comment by mnowotka** [comment]
No, they are sorted by ID. This makes sense as the more popular ones are closer to top. Changing this requires some discussion, assigning Mark.

**Comment by ljbellis** [comment]
Not really. How does a curator know which ones are more popular? 
Alphabetical is the standard.

**Comment by mark-davies** [comment]
These should be alphabetical. 

We should also limit the number of the elements the selector currently has on display. In my browser (firefox 33.1.1) this goes way off the page.

**Comment by mnowotka** [comment]
Fixed, please refresh and verify.

**Comment by ljbellis** [comment]
Yes this works, though it take a second or two for them to appear, but it does work, thanks
