### ISSUE TITLE
New Source asking for Journal?

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#19]
When adding a new source, there is a choice of Scientific Literature. 

Surely, if the user does not pick this one and creates their own, the likelihood is that it's not a paper and more an experimental set - otherwise they would pick Scientific Literatute. Also, it might not be published.

By the way, Create... looks like it means 'Create New Journal' which is what I thought and I clicked on that as my journal wasn't listed and I wanted to add it. It then added a blank document. This is because is it next to Existing and PDF.

Instead of Create, it would be better to have OK.

**Comment by ljbellis** [comment]
Further to this: Maybe good to have 'Type' at the top of this source with free text underneath (or Abstract) and then make it optional to have the Document/Journal information underneath

**Comment by mnowotka** [comment]
`Create` means that a new Document row will be created. 'OK' can be misleading, assigning Mark.

**Comment by ljbellis** [comment]
OK normally means you're happy with what you have entered in the window. 

You use OK for other sections, such as checking the Difference between two compounds when merging or moving records.

**Comment by mnowotka** [comment]
Related to https://github.com/chembl/curation-interface/issues/57.
