### ISSUE TITLE
Can't delete the new compound I just added

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#20]
I created this new compound, saved it and added a source.

Then on the homepage I clicked on 'New Compound' and then 'Delete Compound'

I got an error message saying it couldn't be deleted.

![delete molecule](https://cloud.githubusercontent.com/assets/9843928/5129211/80cf585a-70d8-11e4-9c58-b135b221dbf0.jpg)

**Comment by mnowotka** [comment]
Since we can't make this operation 100% safe when the application is used simultaneously by many users, I've removed this feature from curation interface.
