### ISSUE TITLE
Adding a new compound record to a new compound

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#22]
" Add New Compound Record...."

Document ID - this uses our internal DOC_ID, which is fine and I know what it is, but if I put in the doc_id (say 43521), it would be good to have a Look Up like you have in the 'Find Document' page to see if it's the correct one and I haven't transposed the numbers.

Also, external people won't know too much about doc_ids, so maybe good to have the PubMed or DOI look up here instead.

**Comment by mnowotka** [comment]
You can use `Find document` to check by doc_id.
PubMed and DOI lookups are now working fine.
