### ISSUE TITLE
What is Curated in "Add new compound record..."

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#24]
What is Curated in this sense? Not obvious.

**Comment by mnowotka** [comment]
`Curated` is a name of the column in Compound Record table.

**Comment by ljbellis** [comment]
Can be marked as curated if the entry has been mapped to a molregno other than that given by the original structure, and hence care should be taken when updating.

This isn't something that should be edited at the point is it in your interface. It should be set automatically as 1 if the record is moved due to a split or redraw

**Comment by mnowotka** [comment]
Good to know! I will add some logic to set it when doing split/redraw. Reopening this.

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
yes, this works.
