### ISSUE TITLE
Updated_By and Updated_On need to be editable

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#28]
I would like to be able to edit Updated_By and Updated_On as I use this to keep a track of changes. If this can't be edited, then it would be good to have it automatically filled in with my user name and sysdate when I create the record.

**Comment by mnowotka** [comment]
These fields are automatically updated by curation interface each time you make any change.

**Comment by ljbellis** [comment]
What changes?

I have moved records and merged and these columns haven't been populated.

**Comment by mnowotka** [comment]
Changes like editing a Compound Name or Filename. But you are right this should be changed when moving records as well, I'm marking this as a bug and reopening this.

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
Updated
