### ISSUE TITLE
"Error while saving"

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#3]
If I put a compound into the drawing window,  then click 'save to chembl', it asks if I want to clean it. If I cancel this, I then get a red message saying 'Error While Saving. Cancelled'.

Technically, there's no error, I've just cancelled it. 

Maybe this message could change and separate out the Errors from those actions that are just Cancelled?

**Comment by mnowotka** [comment]
No problem, this will be fixed in the next minor release, I will close this issue when this is deployed.

**Comment by mnowotka** [comment]
Done.
