### ISSUE TITLE
Research Stem when entering a new synonym

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#30]
This should be made for Research Codes only.

I could enter the stem for a non-Research Code synonym

**Comment by mnowotka** [comment]
Fixed, please refresh and verify.

**Comment by ljbellis** [comment]
Yes, it works. Although rather than having that symbol, a tool tip of 'Research Stem for Research Codes only' or something similar would be more useful.

**Comment by mnowotka** [comment]
> Although rather than having that symbol

I don't have any control over this symbol. It is added by web browser for all disabled fields.

> a tool tip of 'Research Stem for Research Codes only'

Sure, I can add the tooltip.
