### ISSUE TITLE
Duplicate Synonyms not being flagged

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#31]
When entering a new synonym that is identical to an existing one in the compound curate page (http://sark.ebi.ac.uk:3021/curation/curate#1763547), you can enter all the details and then click OK and it's not loaded. 

But there is no message to say that it wasn't loaded because it already existed.

**Comment by mnowotka** [comment]
There is no constraint in the database so adding many synonyms with the same name is perfectly valid operation. If this is wrong we should ask Anna to add constraints first. I'm closing this and leaving it for Mark.
