### ISSUE TITLE
Select and Unselect All Synonyms does not work

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#32]
These buttons do nothing http://sark.ebi.ac.uk:3021/curation/curate#1763547

**Comment by mnowotka** [comment]
I can't reproduce this one, some more information is needed here (at least the browser).

**Comment by ljbellis** [comment]
It works in Firefox but not in Chrome

Chrome version Version 38.0.2125.111
Firefox 33.1.1

**Comment by mnowotka** [comment]
OK, I'll check that, thanks!

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
Yes, it works thanks.
