### ISSUE TITLE
Change the 'X' for 'Unselect all synonyms'

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#33]
The 'X' normally means Delete. 

I would change to having a similar system to what we have on our interface where everything is selected by default and by clicking the select box once you deselect everything and by clicking again, you select all.

This is much better.

![x](https://cloud.githubusercontent.com/assets/9843928/5130002/09f4d4c4-70df-11e4-95a7-ab888da99192.jpg)

**Comment by mnowotka** [comment]
This is purely a matter of taste, I've added buttons at the bottom of the table and I'd prefer to keep them. I'm closing this and assigning Mark.
