### ISSUE TITLE
Remove Selected Synonyms Doesn't Work

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#34]
I have tried to remove an added synonym from my page http://sark.ebi.ac.uk:3021/curation/curate#1763547 and this button won't work. I have refreshed and tried again but still no luck.

**Comment by mnowotka** [comment]
Can't reproduce.

**Comment by ljbellis** [comment]
Same thing, works in Firefox, not in Chrome

Chrome Version 38.0.2125.111
Firefox 33.1.1

**Comment by mnowotka** [comment]
OK,  I will test it on Chrome, thanks for reporting.

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
Yes, works. Thanks
