### ISSUE TITLE
Error when putting ChEMBL ID in the URL

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#36]
When I wanted to curate sildenafil, I could only remember its ChEMBLID so I typed that in the URL

http://sark.ebi.ac.uk:3021/curation/curate#CHEMBL192

I got this error message

![sildenafil](https://cloud.githubusercontent.com/assets/9843928/5130137/07a1f8a4-70e0-11e4-9c0b-46d79e2be567.jpg)

**Comment by mnowotka** [comment]
No you can't do this currently, only molregno will work. I will change the label to `enhancement`

**Comment by mnowotka** [comment]
You can use `Search` box in the top toolbar if you have ChEMBL ID.
