### ISSUE TITLE
Clicking on Replacement molregno 'null' gives error

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#38]
When I clicked on the 'null' in replacement molregno in Meta, i got a new pop up window with 
this message

![sildenafil](https://cloud.githubusercontent.com/assets/9843928/5130426/5d41fa28-70e2-11e4-80cc-25be6241e0f1.jpg)

**Comment by mnowotka** [comment]
Fixed. Please refresh and verify.

**Comment by ljbellis** [comment]
No pop up, but I can't enter a Molregno now at all

**Comment by mnowotka** [comment]
No you can't because this is a read-only field. Replacement molregno is added automatically when you redraw a compound or (this will be added soon by fixing #82) downgrade the previous one.

**Comment by ljbellis** [comment]
This has been discussed and we are in agreement at what is required
