### ISSUE TITLE
When doing a Split, make 'Check' available

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#39]
I have drawn a new compound and clicked on 'Split'.

The pop up window 'Split Compound' comes up and I entered in the ChEMBL ID I wanted to use.

However, even once I had entered the ID, 'check' and 'Diff' stayed greyed out.  

It would be good if as soon as the molregno/chemblid field is populated these buttons become active as it's not obvious how to activate them (I used carriage return in the end).

**Comment by mnowotka** [comment]
Both buttons are now always enabled.
