### ISSUE TITLE
Curate window - Click on USAN_SubStem brings a pop up

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#4]
Find a structure in ChEMBL and then click on Curate.

In the Curate window, click on 'null' next to USAN Substem and a pop up window that says 'Loading compound data' comes up. 

Nothing happens and you eventually have to  close the window.

**Comment by mnowotka** [comment]
Can you provide a link?

**Comment by ljbellis** [comment]
Nope, works each time. You're welcome to come and see

**Comment by ljbellis** [comment]
http://sark.ebi.ac.uk:3021/curation/curate#16789

**Comment by mnowotka** [comment]
This is now fixed and USANs are currently read-only. I've created a new question, where read/write functionality should be discussed: https://github.com/chembl/curation-interface/issues/51
