### ISSUE TITLE
Record Id in Split Compound - can you add more than one?

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#41]
Often, I have to split, say 3 records out of 7, from one compound to a new one. 

I would, therefore, have a list of record ids that I would like to use. 

Can I put in more that one into the record ID field and if so, how are they separated?

It would be good to have some guidance to this in the box

**Comment by mnowotka** [comment]
You click `find records` and click and select all records you want to move from the list.

**Comment by ljbellis** [comment]
I have done this and noticed that they are separated by ',' so I will assume that I can do that as well?

**Comment by mnowotka** [comment]
Yes.
