### ISSUE TITLE
record id - find records?

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#42]
it would be good to put in a molregno/chembl id from the old compound you're using for a split and then when you click on Find Records it lists all of them as there could be, maybe a list of 10 that you want to move and don't want to have to type them all in.

**Comment by mnowotka** [comment]
I think it works exactly this way but let's check together.

**Comment by mnowotka** [comment]
Since we have this: https://github.com/chembl/curation-interface/issues/86 I'm closing this one.
