### ISSUE TITLE
Don't have ChEMBL_ID hyperlinked for compounds unless they exist

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#44]
http://sark.ebi.ac.uk:3021/curation/curate#1763548

Just added this compound and ChEMBLID in identifiers is hyperlinked to the interface but as it's a new compound, of course it won't have a page so no point having this active unless the compound is from a previous release.

**Comment by mnowotka** [comment]
Yes, this is true. But please note that the public interface is a completely different piece of software then curation interface. Curation interface have no way to check if the compound page already exists in the public interface. Still this is quite useful to have such a link. So I think that for know this is enough if the user knows that the link can be broken.

**Comment by ljbellis** [comment]
I completely understand that the public interface is completely difference to the curation interface. Which is why I bring up the point of there being a hyperlink.

As they are two different entities, I don't think there is a need to have a hyperlink to the original interface page as all the same information is shown in the curation page.

If there is a valid use for having the hyperlink, that isn't satisfied by the information shown on the curation interface, then this link could probably stay (even though for most of the compounds that someone would load, this would be defunct)...

**Comment by mnowotka** [comment]
I'm leaving this for Mark to decide.

**Comment by mark-davies** [comment]
Leave the link, but add a quick '*' with a note saying link may work. 

Also might be worth adding a UniChem cross reference section - low priority

**Comment by mnowotka** [comment]
Fixed.

![screen shot 2014-11-25 at 12 45 31](https://cloud.githubusercontent.com/assets/837119/5182985/52735eb2-74a1-11e4-971a-ed7a842a5df3.png)
