### ISSUE TITLE
Canonical Smiles isn't correct

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#47]
Just drew a new compound and loaded it into ChEMBL

The 'New Compound' box that then appears underneath the drawing window shows the new compound.

The canonical smiles that's in the box is incorrect for this compound

The smiles in the Curate window is fine 
http://sark.ebi.ac.uk:3021/curation/curate#1763551

![smiles](https://cloud.githubusercontent.com/assets/9843928/5141594/51ac3592-716f-11e4-9d6b-3114346f0ebd.jpg)

**Comment by mnowotka** [comment]
Fixed.

![screen shot 2014-11-25 at 12 49 30](https://cloud.githubusercontent.com/assets/837119/5182999/8a5959d0-74a1-11e4-99b9-42aa564d2ccd.png)
