### ISSUE TITLE
Canonical smiles 'copy to clipboard' doesn't work on the Curate page

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#48]
http://sark.ebi.ac.uk:3021/curation/curate#1763551

Clicked on the copy to clipboard button for the Smiles and it didn't work.

If I clicked in the field and highlighted it all, I can do Cmd+C from there.

**Comment by mnowotka** [comment]
In general copying to clipboard involves flash plugin. Chrome have it's own implementation of flash, so can you verify if this is Chrome specific issue?

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
Yes this works.
