### ISSUE TITLE
Move record doesn't work as I would expect

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#5]
Search for a compound then click on curate.

Choose a record out of the list and click on the arrow to move that record. Nothing happens.

**Comment by mnowotka** [comment]
Again, a link would be nice. This is probably a general error affecting all compounds but it's always better to look at the same compound.

**Comment by mnowotka** [comment]
OK, got it!

**Comment by ljbellis** [comment]
http://sark.ebi.ac.uk:3021/curation/curate#16789

**Comment by mnowotka** [comment]
Step by step is very helpful! But including a link makes it even more helpful :)

**Comment by mnowotka** [comment]
Fixed, please refresh Curation Interface and verify.

**Comment by ljbellis** [comment]
No, still doesn't work for me

**Comment by mnowotka** [comment]
Did you refresh using cmd+shift+r?

**Comment by ljbellis** [comment]
yes

**Comment by ljbellis** [comment]
wait......it's just started to work
