### ISSUE TITLE
Search box at the top not working as expected

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#53]
If you put in a CHEMBL ID or molregno

(CHEMBL192)

you get a suggestion of a matching compound, which if you click on it opens up a Curate page.

if you go back to the Load page, you will see that the Molregno of that compound is still in the Search box. if you click in this box and hit carriage return, nothing happens. No matching compound is found and no new page is opened.

**Comment by mnowotka** [comment]
Fixed. Please refresh and verify.

**Comment by ljbellis** [comment]
No, still does the same in FF and Chrome. 410802 remains and you can keep hitting carriage return and it does nothing.

**Comment by mnowotka** [comment]
Please make sure you have cleared browser cache. I've tested it and can't reproduce.

**Comment by mnowotka** [comment]
I'll double check this one.

**Comment by mnowotka** [comment]
OK, that was my mistake, can you check once again?

**Comment by ljbellis** [comment]
This now works
