### ISSUE TITLE
Error message when clicking on 'Curation Interface'

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#54]
When in Firefox, I was looking at 

http://sark.ebi.ac.uk:3021/curation/curate#410802

and then wanted to go back to the homepage so I clicked on the logo for 'Curation Interface' in the top left hand corner and I got this error message

![message1](https://cloud.githubusercontent.com/assets/9843928/5142458/90bf9fd4-717a-11e4-97e4-1b379d7b10a6.jpg)

**Comment by mnowotka** [comment]
Fixed.

**Comment by ljbellis** [comment]
Yes, thanks.
