### ISSUE TITLE
There's no 'Save' button or 'Would you like to Save your changes?' button

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#6]
I have just searched for naphthalene (link http://sark.ebi.ac.uk:3021/curation/curate#16789) and i clicked on downgraded.

I looked for a 'Save Changes' button but there was none. So I closed the window thinking my changes hadn't been saved. They had.

There should be a 'commit' or 'save button for this page.

**Comment by mnowotka** [comment]
This one requires some discussion I'm assigning Mark to this issue.

**Comment by mark-davies** [comment]
I see a pop-up when asking if I want to downgrade compound (even when no records attached to molecule). I expected the DB to be updated after I clicked OK, so think this behaviour is fine. Did pop-up not appear? Or are there other changes on this page which may require a pop-up intervention?

**Comment by ljbellis** [comment]
Yes there's a pop up for Downgrade, but nothing if I change a Compound name or SRC_ID for example. 

I think it's more like a confirmation button required? Such as 'Would you like to save all changes'

**Comment by mnowotka** [comment]
No, honestly not. I would like to have my changes saved asap, without any questions. Otherwise, where would I put 'Save' button? Save button below every box (downgrade, identifiers, usans)? One for all? And then what about records - a button on every table row? Or a button on every table (records, synonyms)? As long as save operation is fast and lightweight and doesn't have any serous consequences I'd prefer to have everything saved immediately.

**Comment by ljbellis** [comment]
Well, can't there be a floating message, as you have for everything else, saying 'Changes Committed' so you know it's done something?

Or 'Commit Processed' as you see in SQL.

You might want everything done asap, without questions, but when you're curating, you like some sort of confirmation that the changes you've just made have gone through. Not having anything is not normal process.

**Comment by mark-davies** [comment]
This is tricky thing to implement, lets talk about about it when next all in

**Comment by mnowotka** [comment]
Once we've talked this though I think I can close it safely.
