### ISSUE TITLE
Remove 'Existing' from 'Choose a document'

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#60]
Remove "Existing" from Choose A Document because it asks for the same id as in Document ID in the previous window. 
![screenshot_15](https://cloud.githubusercontent.com/assets/9843928/5144531/344fd386-7193-11e4-9b47-7497ffce6f70.jpg)

**Comment by ljbellis** [comment]
If you have the second window because you can find on a ChEMBL ID, then I would still remove it and replace the first field on the previous window with the 'Document ID or ChEMBL ID' field

**Comment by mnowotka** [comment]
Retated to https://github.com/chembl/curation-interface/issues/57 so closing this one.

**Comment by ljbellis** [comment]
This is not directly related. 

This is a suggestion of combining the Document_id from window 1, with 'Existing' of window 2.

Unless this specific information/request is added to #57 this needs to be talked about.

**Comment by mnowotka** [comment]
It is related to document creation/retrieval and all this will be addressed in one issue #57.
