### ISSUE TITLE
Move Records in Chrome - unexpected activity

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#62]
If I select a couple of records to move, say the two from here http://sark.ebi.ac.uk:3021/curation/curate#1763554
in Chrome and I click on MOve Records, nothing happens initially. If I click a few times, then a few Move Records boxes appear.

If I cancel those and then decide I do want to move the records, then nothing at all happens until I refresh the page.

**Comment by mnowotka** [comment]
Can you please check if it works now?

**Comment by ljbellis** [comment]
this works!
