### ISSUE TITLE
Compound Image on the Curate page

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#63]
Why do you have the compound image right next to the compound window on the curate page?

http://sark.ebi.ac.uk:3021/curation/curate#1763554

Is there any need for it to be there at all?

**Comment by mnowotka** [comment]
Yes. Compound image and current sketch inside Marvin are two different things. Maybe currently existing image is broken (for example we have exotic compound which marvin can handle easily but software responsible for generating an image can't render it correctly).

**Comment by ljbellis** [comment]
Exotic? Such as? Do you have an example?

It looks a bit redundant and unnecessary as they're so close together, but if you have examples of where Marvin can handle some structures that the image renderer can, I'd like to have a look at them please?

**Comment by mnowotka** [comment]
Will do.

**Comment by ljbellis** [comment]
Excellent. Might be a good way to flag up bad compounds that slip through the net.

**Comment by mnowotka** [comment]
https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1172371
https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2179464

**Comment by ljbellis** [comment]
I still think we should just stick with Marvin as the only viewer.

**Comment by mark-davies** [comment]
I think it is important to see the image which generated for the compound as it is independent from the sketcher. This is how the compound appears to users in searches, report card, web services etc and it is best to know if it looks wrong.

**Comment by mnowotka** [comment]
I have even better example: http://sark.ebi.ac.uk:3021/curation/curate#1112
