### ISSUE TITLE
There's no cancel button on the Choose A Document page

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#64]
There's no obvious cancel button on this window. 

Yes, there's a cross in the top right, but it's not obvious.

It would be good to have something at the bottom with the others.

![screenshot_16](https://cloud.githubusercontent.com/assets/9843928/5144876/fa92795c-7195-11e4-8e00-d203d625f45d.jpg)

**Comment by mnowotka** [comment]
IMO this would make the window too wide. Leaving this for Mark to decide.

**Comment by ljbellis** [comment]
I did suggest removing 'existing' as this could be on the first window. I also suggested changing 'create' to 'ok' as create is misleading. Both of these suggestions would reduce the width.

**Comment by mnowotka** [comment]
Yes true. But this just means redesigning this dialog, which I agree should happen but in order to do this we should sit together and discuss.

**Comment by mnowotka** [comment]
Related to https://github.com/chembl/curation-interface/issues/57 so closing this one.
