### ISSUE TITLE
Internal error when adding an invalid year

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#65]
I was in Choose A Document and decided to add the year 6789 and nothing else and clicked on create.

I got this error message

![screenshot_17](https://cloud.githubusercontent.com/assets/9843928/5144971/c44130ae-7196-11e4-9de4-598da445fc5b.jpg)

**Comment by mnowotka** [comment]
Fixed.

![screen shot 2014-11-25 at 12 58 58](https://cloud.githubusercontent.com/assets/837119/5183121/d8b9a340-74a2-11e4-9b50-ad33e426f31e.png)
