### ISSUE TITLE
Allows you to create a completely blank document

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#66]
Go to Add a new compound record, http://sark.ebi.ac.uk:3021/curation/curate#1763554, click on Find Document and then just click on Create

This gives you a valid doc id but there's nothing linked to it.

You should be made to at least add some information

If they have chosen 'Publication' then the minimum should be Journal, year, volume and issue.

If it is a book the minimum should be ISBN number

If it is a dataset then they should have to add some sort of experimental description

**Comment by mnowotka** [comment]
Yes, you can create a completely blank document. True. This is because there is no constraint on Docs table. It there is no restrictions at database level I'm not going to add any myself. This should be discussed with Mark and Anna.

**Comment by ljbellis** [comment]
I'd like to be part of that conversation please, so if this is discussed, please make sure to let me know. Thanks.

**Comment by mnowotka** [comment]
Sure! On Monday I'll ask Mark to create account for Anna here and this should hopefully solve the problem.

**Comment by ljbellis** [comment]
I would thank sitting down together would be better. We can see it live and discuss the requirements. Much better than back and forth on here
:)

I think that would be better......?

**Comment by mnowotka** [comment]
Yes, sure - sitting down together is important and having Anna to participate in github issues regarding database is important as well.

**Comment by mnowotka** [comment]
Since Anna is here on GitHub now I'm assigning her to this one.

**Comment by agaulton** [comment]
Depending on the publication type, various columns are allowed to be null or not, so it's not possible to use simple constraints. However, I could add some more complex check constraints to the table. Louisa is correct though - it makes sense that if a publication all the journal/citation details are present, and if a dataset it needs a title at least. Let me know if you want me to add some constraints.
