### ISSUE TITLE
Existing on Choose A Document should populate the fields

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#67]
When in 'Choose A Document' and you click on Existing and use a ChEMBL ID (e.g. CHEMBL3124784), and click OK, the fields in 'Choose A Document' should be populated, as they are with PubMed ID and not go straight back to "Add a new compound record".

I am sure the user would like to make sure that they have added the right document

**Comment by mnowotka** [comment]
Related to https://github.com/chembl/curation-interface/issues/57.

**Comment by ljbellis** [comment]
This is talking about the feature of Existing _if_ it stays where it is. Therefore, not directly linked to #57.

**Comment by mnowotka** [comment]
I've already explained my view on issues related to document creation/retrieval in many other places. I'm closing this one because we have one central issue addressing this problem, assigning Mark and tagging as let's talk.
