### ISSUE TITLE
Clicking on Doc ID in the Curate window does not bring up the document information

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#68]
Once i had entered my new record id in http://sark.ebi.ac.uk:3021/curation/curate#1763554 (rec id 2133348) I clicked on the Doc ID of 77245, which is an existing document in CHEMBL.

It gave me the pop up window for 'Choose a document" but the fields weren't populated. 

It would be more useful to have these fields populated because maybe you want to see what doc you've just linked them to, or maybe you want to add something like the abstract to it. How would you know that it's the right document for your record?

**Comment by ljbellis** [comment]
![screenshot_23](https://cloud.githubusercontent.com/assets/9843928/5164632/efab490e-73d1-11e4-8622-674ebbd7b25c.jpg)

Just in case it helps.

**Comment by mnowotka** [comment]
If you click on the document id this means you want to change it to something else. I wanted to the user so instead of asking for raw document_id which is meaningless number I present a dialog which helps to create/find a document and replace old doc_id with the new one.

I'm closing this issue now as this is directly related to https://github.com/chembl/curation-interface/issues/57

**Comment by ljbellis** [comment]
Not necessarily. It might just mean that I want to add some information to it. Like an abstract. Or maybe I just wanted to have a look and see what document it referred to.

Due to the number of compounds that can be attached to a single document, it would be very very unlikely that the document would be changed at this level. It would be more likely to be changed in the database.

There 'may' be a scenario where I would want to alter the document that I have just linked my new record to, but it might be a small change, say the year or the issue but it would be useful and necessary to see what information is already there.

It is not useful that it is a blank pop up window.

**Comment by mnowotka** [comment]
Fair point I will most probably change it to be pre populated with current data. We should only discus the details.
