### ISSUE TITLE
After saving a compound Downgraded, then can't find it by structure searching

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#7]
I downgraded Naphthalene, by accident, but then when I went back to search for the structure it wasn't found. I assume because of it's downgraded status.

I know that if I knew its molregno, I could find it by using the link http://sark.ebi.ac.uk:3021/curation/curate#16789, however, that's not really intuitive. 

I think it would be good to still be able to find a downgraded compound by structure but make the 'This compound is downgraded' banner bigger so they know.

I have just tried to LOAD this compound as it wasn't found (so pretending I was a new user and wanted to load this structure) and I get all sorts of errors because it already exists. Some errors say it can't be loaded because it exists then you get it successsfully loaded into the molecule dictionary!! Confusing

**Comment by mnowotka** [comment]
Fixed, please refresh (cmd+shift+r) and verify.

**Comment by ljbellis** [comment]
Yes, works. thanks.
