### ISSUE TITLE
The 'Reset' button keeps disappearing

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#70]
Both Chrome and FF

When you are adding a record and click on Find A Document, the first you click there is no Reset button in Choose A Document. But if you add anything, or choose Default, go back to Add A Document and then click on Find A Document, you suddenly have a reset button.

**Comment by mnowotka** [comment]
`Reset` only makes sense when you have chosen a Document. If no Document is selected there is nothing to reset.

**Comment by ljbellis** [comment]
Not really. It's good to have from the start.

Example scenario:
Enter a pubmed id and you populate the fields, but then you realise that it's not the right one. It would be good and useful to have a reset button to clear the fields so you can start again. 

This would also work if you were entering the data by hand and then wanted to start again.

It's odd to have a button that is not there one minute and there the next. 

If you set the doc as 'default', nothing is populated as standard but you still get a reset button.....even though there's no document 

Maybe it could be better that you have a reset button but it's greyed out until you've entered data. Compromise?

**Comment by mnowotka** [comment]
We are talking about two different functions of the `Reset` button.

What `Reset` button currently does, it resets the chosen document. I doesn't have anything to do with cleaning fields in the dialog. And resetting this choice is a very important functionality.

I can add a button that cleans all fields in the dialog but I don't think this is critical right now.

**Comment by ljbellis** [comment]
So please explain what Reset does in this context? What do you mean 'resets the chosen document' that is different to clearing the form to load another document ?

Because when I used it, I found a pubmed id, went back to the Add a document window and before saving it, went back into Find Document and clicked  reset to clear the fields so i could change the document to a hand filled in data set. That is the normal function of Reset in the context of adding new information before saving.

**Comment by ljbellis** [comment]
Just to be clear.....

I've added the data for a document 
Gone back to the Add a document window
Decided to change the document
Gone back to Fjnd A Document
Pressed reset
The fields have been cleared
I've changed the data to another pubmed id

**Comment by mnowotka** [comment]
When loading new compounds to ChEMBL you have to specify from which Source and Document they come from. This is why you have to specify them when loading the first compound.

For example when you click 'Insert new compound' you will be asked to specify source and document. Now you can check that in the bottom of the curation interface you can see ID's of chosen source and document. As long as they are set, curation interface won't ask you to specify source and document anymore. But you may decide to change it or reset - so leave it unspecified and this is what reset button is for.

I can explain it better on Monday.

**Comment by ljbellis** [comment]
Yes I think that would be wise. 

Especially as my example, described above, is not the same example as you're describing and a completely different scenario to which you're thinking about. 

This issue also links in nicely with restricting blank documents being added (previous discussion)

We need to think carefully about making sure that the terms we use are universal across different sectors. When in doubt, we need to implement tool tips or messages explaining consequences of certain actions (like when we have 'are you sure you want to downgrade this compound').

**Comment by mnowotka** [comment]
Just linking this to https://github.com/chembl/curation-interface/issues/57 to keep this issue in mind.
