### ISSUE TITLE
Added a Pubmed ID (14602791) but am allowed to change type

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#73]
I've just looked up a PubMed ID (14602791) and populated the fields with the data. But then I can change the type to Dataset or Book.

I think this should be restricted.

**Comment by mnowotka** [comment]
What if user first look up a PubMed ID and then change his mind and decide to edit all fields by hand?

Anyway, when making a PubMed look up, Type is changed to PUBLICATION by default. I think we can assume that the curator is a reasonable human being and allowing to change this default value to something else if necessary makes sense.
