### ISSUE TITLE
Choose a document - for entering a new compound

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#75]
When you submit a new compound, add or choose a source, it then asks you to add document info for that new compound.

Unlike on the curate page, it doesn't give you the option to add a Doc_ID or ChEMBL_ID look up. I know it's a new compound but I think it would be a good enhancement to have on this 
![screenshot_19](https://cloud.githubusercontent.com/assets/9843928/5145681/c2c49828-719c-11e4-96f8-7f60cb82ce61.jpg)
page.

**Comment by mnowotka** [comment]
Is this anything that we haven't covered when discussing https://github.com/chembl/curation-interface/issues/57?

**Comment by ljbellis** [comment]
yes, this was discussed.

**Comment by mnowotka** [comment]
OK, in that case I'm closing this one.
