### ISSUE TITLE
Source List uses the description in the list rather than the short name

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#76]
When adding a new source you have 

Short Name
Description

as options.

One would think logically that Short Name would be 'Scientific Literature' and the Description would be 'Data extracted from publications"

Therefore, I would add Short name as 'LouisaSource' and Description as 'Source from Louisa'

However, this logic is the other way around.

I would suggest changing it to something like
Description(Displayed on interface)
Short name(iinternal use only)

so that they are aware it's the other way around.

**Comment by mark-davies** [comment]
I would leave as is, as it reflects what is in the database.

It probably makes sense to add the the short_name to the table so that people are aware of the format - not many characters, no whitespace, all uppercase. We could even have a format constraint on this.
