### ISSUE TITLE
When entering a new compound, you are asked to click on 'Insert A New Compound' Twice

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#78]
I drew a new compound.
Clicked on 'Insert new compound'
Clicked on an existing source and then 'OK'

The window closed and I was left with the original 'Action Required' window (pictured) and I can then click on 'Insert new compound' again, but I also clicked cancel and the compound was not added (I searched for it).

I then clicked on Save To ChEMBL again and got this error message

![screenshot_22](https://cloud.githubusercontent.com/assets/9843928/5164368/c67e61ae-73ce-11e4-84fc-b79fe1d91e18.jpg)

**Comment by mnowotka** [comment]
Can you check if the problem still occurs?
