### ISSUE TITLE
Can't alter the structure in the Curate window

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#8]
I searched for naphthalene http://sark.ebi.ac.uk:3021/curation/curate#16789 and then decided that all the records and all the data needed to be linked to another structure. This happens often. 

However, when in the curate window, I altered the structure in the window and clicked on 'save all to chembl' and nothing happened. The changes were not saved.

**Comment by mnowotka** [comment]
I can't reproduce this one. I need some more information.

**Comment by ljbellis** [comment]
Ok, if you draw a whole new compound
http://sark.ebi.ac.uk:3021/curation/curate#1763551
and then you see in the curate window that it's missing a methyl, you edit the structure to show this and then click on the 'Save Updates To ChEMBL' button below the sketcher.

The structure changes aren't saved.

Feel free to come and see what I mean....

**Comment by mnowotka** [comment]
Fixed, please verify.

**Comment by ljbellis** [comment]
yes fixed.
