### ISSUE TITLE
When adding a new record to a compound, it would be good to use 'Filename' as a source description

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#80]
Currently, when we add data to the database, we use the Filename column as a sub-description of this data.

So, for viagra, we have the molconn version, or the subset of data it came from

![screenshot_29](https://cloud.githubusercontent.com/assets/9843928/5164883/f717d4c0-73d4-11e4-925c-c52d94ffc5f3.jpg)

At the moment, when you add a new record to a compound, you are only prompted for Source: which is Literature, Grac, GSK etc. So you end up with a blank filename

![screenshot_27](https://cloud.githubusercontent.com/assets/9843928/5164898/1182da12-73d5-11e4-9499-8ddf929594e0.jpg)

it would be good to have Source Description under Source so someone could add
"GSK Kinase data set January 2015" for example......

This also helps to note when it was deposited, which is useful.

**Comment by mnowotka** [comment]
Done.
![screen shot 2014-12-01 at 14 17 34](https://cloud.githubusercontent.com/assets/837119/5246816/d7245cca-7964-11e4-8e0e-fadd8bbea0c4.png)

**Comment by ljbellis** [comment]
brilliant, thanks.
