### ISSUE TITLE
Why do you link to a source when adding a new compound?

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#81]
When you add a new compound, you are prompted to link it to a source and even a document.

However, when this compound is then added, there seems to be no link to this anymore.

Where does this linkage go?

Surely a default compound record should be added with this information, as it is for new compounds not linked to data, like USANs and Orange Books?

**Comment by mnowotka** [comment]
Every CompoundDictionary needs at least one CompoundRecord. In order to create new Compound Record you have to specify Source and Docs.

![full_dep](https://cloud.githubusercontent.com/assets/837119/5182526/4ca048ac-749b-11e4-928a-13324f8c4b31.png)

**Comment by ljbellis** [comment]
Ok, but it's not there when you are then in the curate window.

I would expect to see the compound record but it's not there. Hence why I am asking where it goes.....

**Comment by mnowotka** [comment]
> Ok, but it's not there when you are then in the curate window.

Can you explain?
