### ISSUE TITLE
When adding a new Document, can you highlight the essential areas

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#87]
When adding a new document in 'Choose New Document'

Can you highlight the boxes that are essential to be filled in before creating that document?

e.g. if you choose type Book, then Title, Authors must be ringed in red?
Publication must have title, author and journal highlighted?

By 'essential' - I mean the minimum amount of information we need in order to enter these documents in to the database

**Comment by mnowotka** [comment]
This is fixed. Please verify.

**Comment by ljbellis** [comment]
Yes, these fields are highlighted. 

However, FIRST PAGE should also be essential.

**Comment by mnowotka** [comment]
OK, so according to this issue: https://github.com/chembl/curation-interface/issues/130 FIRST PAGE shouldn't be essential but I'm happy to change it. But I guess if it is essential, then only for PUBLICATION and BOOK not for DATASET, I'm I right?

**Comment by ljbellis** [comment]
Only for Publication. thanks

**Comment by mnowotka** [comment]
OK, fixed, please take a look.

**Comment by ljbellis** [comment]
Yes
