### ISSUE TITLE
Don't need ChEBI_IDs in the identifiers

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#9]
I would personally remove ChEBI references from the curate page. Internally, I would never use them for curaiton and doubt anyone else would

**Comment by mnowotka** [comment]
Since this is a valid column in MoleculeDictionary table it is shown in the interface. This one requires some discussion, I'm assigning Mark here.

**Comment by mark-davies** [comment]
We should keep the chebi_id references
